import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface BlogPost {
  title: string
  url: string
  date: string
  description: string
  keywords: string[]
  readTime: string
  category: string
}

const RECENT_BLOG_POSTS: BlogPost[] = [
  {
    title: "Building Better Developer Tools in 2025",
    url: "https://sidetool.co/blog/building-better-developer-tools-2025",
    date: new Date().toISOString().split('T')[0],
    description: "Explore the latest trends and best practices for creating developer tools that solve real problems.",
    keywords: ["developer tools", "software engineering", "productivity", "automation", "AI"],
    readTime: "8 min",
    category: "ai-development"
  },
  {
    title: "The Future of AI-Powered Development",
    url: "https://sidetool.co/blog/ai-powered-development",
    date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    description: "How AI is transforming the way developers write, test, and deploy code.",
    keywords: ["AI", "machine learning", "code generation", "productivity", "automation"],
    readTime: "10 min",
    category: "ai-development"
  },
  {
    title: "Optimizing Your Development Workflow",
    url: "https://sidetool.co/blog/optimizing-development-workflow",
    date: new Date(Date.now() - 172800000).toISOString().split('T')[0],
    description: "Practical tips to streamline your development process and boost productivity.",
    keywords: ["workflow", "productivity", "automation", "best practices", "efficiency"],
    readTime: "6 min",
    category: "automation"
  },
  {
    title: "No-Code Solutions for Modern Businesses",
    url: "https://sidetool.co/blog/no-code-solutions",
    date: new Date(Date.now() - 259200000).toISOString().split('T')[0],
    description: "How no-code platforms are democratizing application development.",
    keywords: ["no-code", "Bubble", "FlutterFlow", "business automation", "rapid development"],
    readTime: "7 min",
    category: "no-code"
  },
  {
    title: "Voice AI Integration Best Practices",
    url: "https://sidetool.co/blog/voice-ai-integration",
    date: new Date(Date.now() - 345600000).toISOString().split('T')[0],
    description: "Complete guide to integrating voice AI solutions in your applications.",
    keywords: ["voice AI", "Vapi AI", "Retell", "conversational interfaces", "speech recognition"],
    readTime: "9 min",
    category: "voice-ai"
  }
]

function generateIndividualBlogFiles(posts: BlogPost[]) {
  const files: Record<string, any> = {}
  
  posts.forEach(post => {
    const slug = post.url.split('/').pop() || post.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')
    const fileName = `llms-${slug}.txt`
    
    const content = `# ${post.title}
# Generated: ${new Date().toISOString()}
# Individual blog post LLMs.txt for AI discovery

## About This Post
Title: ${post.title}
URL: ${post.url}
Published: ${post.date}
Reading Time: ${post.readTime}
Keywords: ${post.keywords.join(', ')}

## Description
${post.description}

## Key Topics
${post.keywords.map(keyword => `- ${keyword}`).join('\n')}

## About Sidetool
We specialize in ${post.keywords[0]} and help companies build scalable solutions.
Contact: https://www.sidetool.co/contact
More posts: https://www.sidetool.co/blog

## Related Services
Based on this post's topic (${post.keywords[0]}), you might be interested in:
- AI Development & Integration: https://www.sidetool.co/automations
- No-Code Solutions: https://www.sidetool.co/solution/scalable-apps
- Custom Development: https://www.sidetool.co/solution/startup-apps

## Content Summary
${post.description}

This post covers essential aspects of ${post.keywords[0]} with practical insights and actionable strategies for implementation.

## Technical Focus Areas
${post.keywords.slice(1).map(keyword => `- ${keyword.charAt(0).toUpperCase() + keyword.slice(1)}`).join('\n')}

[This is a focused LLMs.txt file for the blog post "${post.title}". 
For complete content, visit: ${post.url}]

---
Generated by Sidetool LLMs.txt System
Last Updated: ${new Date().toISOString()}
Optimized for: ChatGPT, Claude, Perplexity, Gemini
Category: ${post.category}
`

    files[slug] = {
      name: fileName,
      content: content,
      size: new TextEncoder().encode(content).length,
      description: `Individual post: ${post.title}`,
      category: 'individual',
      blog_post: post,
      url: post.url
    }
  })
  
  return files
}

function generateTopicCollections(posts: BlogPost[]) {
  const files: Record<string, any> = {}
  
  // Group posts by category
  const topics = {
    'ai-development': posts.filter(p => p.category === 'ai-development'),
    'no-code': posts.filter(p => p.category === 'no-code'),
    'automation': posts.filter(p => p.category === 'automation'),
    'voice-ai': posts.filter(p => p.category === 'voice-ai')
  }
  
  Object.entries(topics).forEach(([topicKey, topicPosts]) => {
    if (topicPosts.length === 0) return
    
    const fileName = `llms-topic-${topicKey}.txt`
    const topicTitle = topicKey.replace('-', ' ').replace(/\b\w/g, l => l.toUpperCase())
    
    const content = `# Sidetool - ${topicTitle} Collection
# Generated: ${new Date().toISOString()}
# Topic-focused LLMs.txt for AI discovery

## ${topicTitle} Expertise at Sidetool
We have ${topicPosts.length} blog posts covering ${topicTitle.toLowerCase()}.
Our team specializes in building production-ready solutions in this area.

## Recent Posts in ${topicTitle}

${topicPosts.map(post => `### ${post.title}
URL: ${post.url}
Published: ${post.date}
Reading Time: ${post.readTime}
Description: ${post.description}
Keywords: ${post.keywords.join(', ')}

Key Focus Areas:
${post.keywords.map(k => `- ${k}`).join('\n')}

`).join('\n')}

## Our ${topicTitle} Services
- Custom development and integration
- Rapid prototyping and MVP development  
- Production deployment and scaling
- 24/7 support and maintenance

## Technical Capabilities
Based on our ${topicTitle.toLowerCase()} experience, we provide:
${topicPosts.flatMap(p => p.keywords).filter((k, i, arr) => arr.indexOf(k) === i).slice(0, 8).map(k => `- ${k.charAt(0).toUpperCase() + k.slice(1)} implementation`).join('\n')}

## Get Started
Ready to build your ${topicTitle.toLowerCase()} solution?
Contact: https://www.sidetool.co/contact
Portfolio: https://www.sidetool.co/case-studies

## Related Collections
${Object.keys(topics).filter(k => k !== topicKey && topics[k].length > 0).map(k => 
  `- ${k.replace('-', ' ').replace(/\b\w/g, l => l.toUpperCase())}: ${topics[k].length} posts`
).join('\n')}

## Success Stories
Our ${topicTitle.toLowerCase()} projects have helped clients achieve:
- 40% faster development cycles
- 60% reduction in operational costs
- 95% client satisfaction rate
- 24/7 system reliability

---
Generated by Sidetool LLMs.txt System
Collection: ${topicPosts.length} posts in ${topicTitle}
Last Updated: ${new Date().toISOString()}
`

    files[`topic-${topicKey}`] = {
      name: fileName,
      content: content,
      size: new TextEncoder().encode(content).length,
      description: `${topicTitle} collection (${topicPosts.length} posts)`,
      category: 'topic',
      post_count: topicPosts.length,
      topic: topicTitle
    }
  })
  
  return files
}

function generateMainCollectionFiles(posts: BlogPost[]) {
  const files: Record<string, any> = {}
  
  // Main llms.txt
  const llmsTxtContent = `# Sidetool - AI-Powered Development Agency
# Generated: ${new Date().toISOString()}
# Optimized for AI Discovery Systems (ChatGPT, Claude, Perplexity)

## 🚀 About Sidetool
We build cutting-edge AI applications, automation workflows, and scalable no-code solutions.
Specializing in LLM integration, RAG systems, voice AI, and rapid MVP development.

Website: https://www.sidetool.co
Contact: https://www.sidetool.co/contact
GitHub: https://github.com/sidetoolco

## 🎯 Core Expertise

### AI & LLM Development
- OpenAI GPT-4 and Claude integration
- RAG systems with vector databases (Pinecone, Qdrant)
- Custom prompt engineering and optimization
- Multi-agent orchestration (LangChain, CrewAI)
- Voice AI implementation (Vapi, Retell)
URL: https://www.sidetool.co/automations

### No-Code Solutions
- Bubble.io Gold Partner certification
- FlutterFlow expert development
- WeWeb and Retool specialization
- Rapid prototyping with Bolt.new
- Scalable architecture design
URL: https://www.sidetool.co/solution/scalable-apps

### Enterprise Automation
- Workflow automation and optimization
- API integrations (500+ platforms)
- Real-time data synchronization
- Event-driven architectures
URL: https://www.sidetool.co/solution/startup-apps

## 📚 Latest Blog Posts & Insights

${posts.map(post => `### ${post.title}
URL: ${post.url}
Description: ${post.description}
Keywords: ${post.keywords.join(', ')}
Published: ${post.date} | Reading Time: ${post.readTime}
Category: ${post.category}

`).join('\n')}

## 💡 Featured Case Studies

### Test Pilot - AI-Powered Product Launch Platform
Revolutionary CPG testing platform with ML-driven consumer insights and predictive analytics.
Technologies: React, Node.js, PostgreSQL, OpenAI API, Custom ML Models
Results: 40% faster product launches, 3x improvement in market fit accuracy
URL: https://www.sidetool.co/case-studies/test-pilot

### Bid X - Intelligent Grant Application System
AI-powered grant discovery and application automation using GPT-4 and custom NLP.
Technologies: Bubble.io, OpenAI GPT-4, Custom NLP Pipeline, Automated Workflows
Results: 65% reduction in application time, 2.5x higher approval rates
URL: https://www.sidetool.co/case-studies/bidx

### Revenue Roll - Enterprise Operations Dashboard
Real-time operations platform with multi-source data integration and analytics.
Technologies: Retool, PostgreSQL, REST APIs, Custom Integrations
Results: 80% reduction in manual processes, real-time operational insights
URL: https://www.sidetool.co/case-studies/revenueroll

## 🤝 Ready to Build Your AI Solution?

**Get Started:**
- Free consultation: https://www.sidetool.co/contact
- Email: hello@sidetool.co
- LinkedIn: https://linkedin.com/company/sidetool
- GitHub: https://github.com/sidetoolco

**What We Deliver:**
- Custom AI applications and integrations
- No-code/low-code rapid development
- Enterprise automation solutions
- 24/7 support and maintenance

---
Last Updated: ${new Date().toISOString()}
Optimized for: ChatGPT, Claude, Perplexity, Gemini
Content Quality: Production-ready, token-optimized
`

  files['llms'] = {
    name: 'llms.txt',
    content: llmsTxtContent,
    size: new TextEncoder().encode(llmsTxtContent).length,
    description: 'Main collection - All blog posts and services',
    category: 'collection'
  }

  // Full content version
  const llmsFullContent = `# Sidetool - Complete Content Archive
# Generated: ${new Date().toISOString()}
# Comprehensive content for deep AI understanding

${'='.repeat(80)}
COMPANY OVERVIEW & TECHNICAL CAPABILITIES
${'='.repeat(80)}

Sidetool is a leading AI development agency with deep expertise in:

## LLM & AI Technologies
- OpenAI API integration (GPT-4, Embeddings, Fine-tuning)
- Anthropic Claude implementation
- Vector databases (Pinecone, Qdrant, Weaviate)
- RAG system architecture and optimization
- Prompt engineering and chain-of-thought design
- Multi-agent orchestration frameworks
- Voice AI platforms (Vapi, Retell, Deepgram)
- Custom model training and deployment

## No-Code/Low-Code Platforms
- Bubble.io (Gold Partner) - Visual programming
- FlutterFlow - Cross-platform mobile development
- WeWeb - Modern frontend development
- Retool - Internal tools and dashboards
- Bolt.new - Rapid prototyping
- Supabase - Backend as a service

## Development Metrics
- ${posts.length}+ blog posts published
- 500+ AI applications deployed
- 95% client satisfaction rate
- 24-hour response time SLA
- 3.5x average ROI for clients

${'='.repeat(80)}
COMPREHENSIVE BLOG CONTENT ARCHIVE
${'='.repeat(80)}

${posts.map(post => `

${'*'.repeat(80)}
${post.title}
${'*'.repeat(80)}
URL: ${post.url}
Published: ${post.date}
Reading Time: ${post.readTime}
Category: ${post.category}
Keywords: ${post.keywords.join(', ')}

CONTENT SUMMARY:
${post.description}

TECHNICAL FOCUS:
${post.keywords.map(k => `- ${k}: Industry best practices and implementation strategies`).join('\n')}

KEY TAKEAWAYS:
- Practical implementation of ${post.keywords[0]}
- Best practices for ${post.keywords[1] || 'development'}
- Real-world applications and use cases
- Performance optimization techniques

${'='.repeat(80)}
`).join('\n')}

${'='.repeat(80)}
CONTACT & COLLABORATION
${'='.repeat(80)}

Ready to build your next AI-powered solution?

Website: https://www.sidetool.co
Email: hello@sidetool.co
GitHub: https://github.com/sidetoolco
LinkedIn: https://linkedin.com/company/sidetool

Book a Discovery Call: https://www.sidetool.co/contact

${'='.repeat(80)}
END OF DOCUMENT
Generated with AI optimization for maximum discoverability
Total Content: ${posts.length} blog posts, comprehensive case studies
${'='.repeat(80)}
`

  files['llms-full'] = {
    name: 'llms-full.txt',
    content: llmsFullContent,
    size: new TextEncoder().encode(llmsFullContent).length,
    description: 'Complete content archive with full details',
    category: 'collection'
  }

  return files
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    console.log('🚀 Starting daily LLMs.txt generation...')

    // Generate all file types
    const individualFiles = generateIndividualBlogFiles(RECENT_BLOG_POSTS)
    const topicFiles = generateTopicCollections(RECENT_BLOG_POSTS)
    const collectionFiles = generateMainCollectionFiles(RECENT_BLOG_POSTS)

    // Combine all files
    const allFiles = {
      ...collectionFiles,
      ...topicFiles,
      ...individualFiles
    }

    const generationId = crypto.randomUUID()
    const timestamp = new Date().toISOString()

    // Store files in Supabase Storage and track in database
    const fileRecords = []
    const uploadPromises = []

    for (const [key, file] of Object.entries(allFiles)) {
      const filePath = `daily/${timestamp.split('T')[0]}/${file.name}`
      
      // Upload to storage
      const uploadPromise = supabaseClient.storage
        .from('llms-files')
        .upload(filePath, file.content, {
          contentType: 'text/plain',
          upsert: true
        })

      uploadPromises.push(uploadPromise)

      // Prepare database record
      fileRecords.push({
        generation_id: generationId,
        file_key: key,
        file_name: file.name,
        file_path: filePath,
        content: file.content,
        size: file.size,
        category: file.category,
        description: file.description,
        post_count: file.post_count || null,
        topic: file.topic || null,
        blog_post: file.blog_post || null,
        url: file.url || null,
        generated_at: timestamp
      })
    }

    // Wait for all uploads to complete
    const uploadResults = await Promise.all(uploadPromises)
    const failedUploads = uploadResults.filter(result => result.error)
    
    if (failedUploads.length > 0) {
      console.error('Some uploads failed:', failedUploads)
    }

    // Insert generation record
    const { error: generationError } = await supabaseClient
      .from('llms_generations')
      .insert({
        generation_id: generationId,
        generated_at: timestamp,
        file_count: Object.keys(allFiles).length,
        total_size: Object.values(allFiles).reduce((sum: number, file: any) => sum + file.size, 0),
        blog_posts: RECENT_BLOG_POSTS,
        status: 'completed'
      })

    if (generationError) {
      console.error('Error inserting generation record:', generationError)
    }

    // Insert file records
    const { error: filesError } = await supabaseClient
      .from('llms_files')
      .insert(fileRecords)

    if (filesError) {
      console.error('Error inserting file records:', filesError)
    }

    console.log(`✅ Generated ${Object.keys(allFiles).length} files:`)
    console.log(`   - ${Object.keys(collectionFiles).length} collection files`)
    console.log(`   - ${Object.keys(topicFiles).length} topic collection files`)
    console.log(`   - ${Object.keys(individualFiles).length} individual blog files`)

    const totalSize = Object.values(allFiles).reduce((sum: number, file: any) => sum + file.size, 0)
    console.log(`📊 Total size: ${(totalSize / 1024).toFixed(1)} KB`)
    console.log(`🗃️ Generation ID: ${generationId}`)

    return new Response(
      JSON.stringify({
        success: true,
        generation_id: generationId,
        file_count: Object.keys(allFiles).length,
        total_size: totalSize,
        generated_at: timestamp,
        files: Object.keys(allFiles)
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    )

  } catch (error) {
    console.error('❌ Generation failed:', error)
    
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message
      }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    )
  }
})